name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint (placeholder)
        run: npm run lint || echo "No lint configured"

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test -- --run
        env:
          CI: true

      - name: Upload build artifact
        if: success() && hashFiles('dist/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: warn

      # Future: add CD steps (e.g., deploy to Pages or container registry)

